name: Run in Renode
description: Runs a specified sample in Renode
inputs:
  path:
    description: Path to the sample
    required: true
  test:
    description: Path to the test file
    required: true
  build-params:
    description: Additional build parameters
    required: false
    default: ''

runs:
  using: "includes"
  steps:
    - name: Fetch toolchain
      run: |
        wget -O- https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz | tar -xzC /opt
        echo "/opt/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin" >> $GITHUB_PATH
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Setup environment
      run: bash scripts/setup -ci
    - name: Build sample
      run:
        pwd && source environment && cd ${{ inputs.path }} && make ${{ inputs.build-params }} -j8 software && cp build/software.elf renode/

    - name: Run tests
      uses: antmicro/renode-actions/test-in-renode@main
      with:
        renode-version: '1.12.0+20210403git44d6786'
        tests-to-run: ${{ inputs.test }}
    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          report.html
          log.html
          robot_output.xml

