name: check-doc-sw
on: [push, pull_request]
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: pwd && cd docs && pwd 
      - run: pwd && cd .. && pwd 
      - run: pwd && cd docs && pip3 install -r requirements.txt && make html && ls -R
  check-sw:
    runs-on: ubuntu-latest
    steps:
      - run: wget -O- https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz | tar -xzC /opt
      - run: echo "/opt/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: bash scripts/setup -ci
      - run: which pip3 && which python3 && which pip
      - run: riscv64-unknown-elf-gcc --version
      - run: pwd && source environment && cd proj/mnv2_first && pip3 list && make -j9 software
      - run: pwd && source environment && cd proj/mnv2_first && pip3 list && make PLATFORM=sim unit
