name: Sync from tflite-micro

on:
  schedule:
    - cron: 0 0 * * *

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  sync-tflite-micro:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'

    env:
      GH_SERVICE_ACCOUNT_NAME: "GitHub"
      GH_SERVICE_ACCOUNT_EMAIL: "noreply@github.com"

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Configure git
        run: |
          git config --global user.name $GH_SERVICE_ACCOUNT_NAME
          git config --global user.email $GH_SERVICE_ACCOUNT_EMAIL

      - name: Sync the code, commit and push
        run: |
          export TFLM_SHA=$(git ls-remote https://github.com/tensorflow/tflite-micro.git main | cut -c1-7)
          ./scripts/sync_from_tflite_micro.sh
          git add *

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Sync from tflite-micro at $TFLM_SHA."
          else
            echo "no changes"
          fi

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: sync-from-tflite-micro
          base: main
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          title: (CFU Playground) Automated sync from github.com/tensorflow/tflite-micro
          commit-message: Automated sync from github.com/tensorflow/tflite-micro
          body: "(CFU Playground) Automated sync from github.com/tensorflow/tflite-micro"
