name: Run in Renode
on: [push, pull_request, workflow_dispatch]
jobs:
  proj_template:
    runs-on: ubuntu-20.04
    steps:
      - includes: /run-in-renode
        with:
          path: proj/proj_template
          test: proj/proj_template/renode/litex-vexriscv-tflite.robot
